server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/smart_attendance

# JWT
app.jwt.secret=ChangeThisSecretKeyToSomethingLongAndRandom
app.jwt.expiration-minutes=480

# Flask AI service
app.ai.base-url=http://127.0.0.1:5000
app.face.min-score=0.78

# CORS
app.cors.allowed-origins=http://localhost:8000,http://127.0.0.1:8000
